"""Add message timestamp

Revision ID: 32ee4b438fdd
Revises: 866eee45ccc6
Create Date: 2026-08-15 19:35:52.627260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ee4b438fdd'
down_revision: Union[str, Sequence[str], None] = '866eee45ccc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
