"""Add conversation summary

Revision ID: b5205f7a9263
Revises: 9f2f6b0be99c
Create Date: 2026-08-21 23:49:03.324483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5205f7a9263'
down_revision: Union[str, Sequence[str], None] = 'bb42c3c5cb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
